*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZDEEC_V001......................................*
FORM GET_DATA_ZDEEC_V001.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZDEEC_T002 WHERE
(VIM_WHERETAB) .
    CLEAR ZDEEC_V001 .
ZDEEC_V001-MANDT =
ZDEEC_T002-MANDT .
ZDEEC_V001-CHAIN_PROCESS =
ZDEEC_T002-CHAIN_PROCESS .
ZDEEC_V001-STEP =
ZDEEC_T002-STEP .
ZDEEC_V001-ADAPTER =
ZDEEC_T002-ADAPTER .
ZDEEC_V001-DATA_SOURCE =
ZDEEC_T002-DATA_SOURCE .
ZDEEC_V001-CUSTOM_CLASS_STEP =
ZDEEC_T002-CUSTOM_CLASS_STEP .
ZDEEC_V001-OBJECT_NAME =
ZDEEC_T002-OBJECT_NAME .
ZDEEC_V001-VARIANT =
ZDEEC_T002-VARIANT .
    SELECT SINGLE * FROM ZDEEC_T001 WHERE
CHAIN_PROCESS = ZDEEC_T002-CHAIN_PROCESS .
    IF SY-SUBRC EQ 0.
ZDEEC_V001-DESCRIPTION =
ZDEEC_T001-DESCRIPTION .
    ENDIF.
<VIM_TOTAL_STRUC> = ZDEEC_V001.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZDEEC_V001 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZDEEC_V001.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZDEEC_V001-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZDEEC_T002 WHERE
  CHAIN_PROCESS = ZDEEC_V001-CHAIN_PROCESS AND
  STEP = ZDEEC_V001-STEP .
    IF SY-SUBRC = 0.
    DELETE ZDEEC_T002 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZDEEC_T002 WHERE
  CHAIN_PROCESS = ZDEEC_V001-CHAIN_PROCESS AND
  STEP = ZDEEC_V001-STEP .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZDEEC_T002.
    ENDIF.
ZDEEC_T002-MANDT =
ZDEEC_V001-MANDT .
ZDEEC_T002-CHAIN_PROCESS =
ZDEEC_V001-CHAIN_PROCESS .
ZDEEC_T002-STEP =
ZDEEC_V001-STEP .
ZDEEC_T002-ADAPTER =
ZDEEC_V001-ADAPTER .
ZDEEC_T002-DATA_SOURCE =
ZDEEC_V001-DATA_SOURCE .
ZDEEC_T002-CUSTOM_CLASS_STEP =
ZDEEC_V001-CUSTOM_CLASS_STEP .
ZDEEC_T002-OBJECT_NAME =
ZDEEC_V001-OBJECT_NAME .
ZDEEC_T002-VARIANT =
ZDEEC_V001-VARIANT .
    IF SY-SUBRC = 0.
    UPDATE ZDEEC_T002 ##WARN_OK.
    ELSE.
    INSERT ZDEEC_T002 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZDEEC_V001-UPD_FLAG,
STATUS_ZDEEC_V001-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZDEEC_V001.
  SELECT SINGLE * FROM ZDEEC_T002 WHERE
CHAIN_PROCESS = ZDEEC_V001-CHAIN_PROCESS AND
STEP = ZDEEC_V001-STEP .
ZDEEC_V001-MANDT =
ZDEEC_T002-MANDT .
ZDEEC_V001-CHAIN_PROCESS =
ZDEEC_T002-CHAIN_PROCESS .
ZDEEC_V001-STEP =
ZDEEC_T002-STEP .
ZDEEC_V001-ADAPTER =
ZDEEC_T002-ADAPTER .
ZDEEC_V001-DATA_SOURCE =
ZDEEC_T002-DATA_SOURCE .
ZDEEC_V001-CUSTOM_CLASS_STEP =
ZDEEC_T002-CUSTOM_CLASS_STEP .
ZDEEC_V001-OBJECT_NAME =
ZDEEC_T002-OBJECT_NAME .
ZDEEC_V001-VARIANT =
ZDEEC_T002-VARIANT .
    SELECT SINGLE * FROM ZDEEC_T001 WHERE
CHAIN_PROCESS = ZDEEC_T002-CHAIN_PROCESS .
    IF SY-SUBRC EQ 0.
ZDEEC_V001-DESCRIPTION =
ZDEEC_T001-DESCRIPTION .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZDEEC_V001-DESCRIPTION .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZDEEC_V001 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZDEEC_V001-CHAIN_PROCESS TO
ZDEEC_T002-CHAIN_PROCESS .
MOVE ZDEEC_V001-STEP TO
ZDEEC_T002-STEP .
MOVE ZDEEC_V001-MANDT TO
ZDEEC_T002-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZDEEC_T002'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZDEEC_T002 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZDEEC_T002'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZDEEC_V001 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZDEEC_T002-MANDT =
ZDEEC_V001-MANDT .
ZDEEC_T002-CHAIN_PROCESS =
ZDEEC_V001-CHAIN_PROCESS .
ZDEEC_T002-STEP =
ZDEEC_V001-STEP .
ZDEEC_T002-ADAPTER =
ZDEEC_V001-ADAPTER .
ZDEEC_T002-DATA_SOURCE =
ZDEEC_V001-DATA_SOURCE .
ZDEEC_T002-CUSTOM_CLASS_STEP =
ZDEEC_V001-CUSTOM_CLASS_STEP .
ZDEEC_T002-OBJECT_NAME =
ZDEEC_V001-OBJECT_NAME .
ZDEEC_T002-VARIANT =
ZDEEC_V001-VARIANT .
    SELECT SINGLE * FROM ZDEEC_T001 WHERE
CHAIN_PROCESS = ZDEEC_T002-CHAIN_PROCESS .
    IF SY-SUBRC EQ 0.
ZDEEC_V001-DESCRIPTION =
ZDEEC_T001-DESCRIPTION .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZDEEC_V001-DESCRIPTION .
    ENDIF.
ENDFORM.

* base table related FORM-routines.............
INCLUDE LSVIMFTX .
